version: '3'
services:
  dump978:
    image: ghcr.io/sdr-enthusiasts/docker-dump978:latest
    container_name: dump978
    ports:
      - "30978:30978"
      - "30979:30979"
      - "30980:80"
      - "37981:37981"
      - "37982:37982"
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      - DUMP978_RTLSDR_DEVICE=978
      - DUMP978_SDR_GAIN=autogain
    restart: unless-stopped
    labels:
      - "autoheal=true"
    volumes:
      - /opt/adsb/dump978:/var/globe_history
      - /dev:/dev:ro
    tmpfs:
      - /run:exec,size=64M
      - /tmp:size=64M
      - /var/log:size=32M
